- name: get GeoWave
  git:
    repo: https://github.com/ngageoint/geowave.git
    dest: /home/hadoop/geowave
    depth: 10
  become_user: hadoop

- name: Build GeoWave Accumulo Plugin
  shell: mvn clean install -P accumulo-container-singlejar -DskipITs=true -DskipTests=true -Daccumulo.version=1.7.2 -Dhadoop.version=2.6.0 -Daccumulo.api=1.7
  args:
    chdir: /home/hadoop/geowave
    executable: /bin/bash
  become_user: hadoop

- name: Copy jar to accumulo
  copy:
    src: /home/vagrant/devops/geowave-deploy-0.9.4-SNAPSHOT-accumulo.jar
    dest: /srv/accumulo/lib/
    owner: hadoop
    group: hadoop
    remote_src: yes

- name: configure geowave
  shell: |
    accumulo shell -u root -p lenticular <<EOF
    lenticular
    createuser geowave
    createnamespace geowave
    grant NameSpace.CREATE_TABLE -ns geowave -u geowave
    config -s general.vfs.context.classpath.geowave=hdfs://localhost:9000/accumulo/lib/[^.].*.jar
    config -ns geowave -s table.classpath.context=geowave
    exit
    EOF

    ## configure accumulo geowave user
    cat <<EOF | accumulo shell -u root -p lenticular -e "createuser geowave"
    geowave
    geowave
    EOF
    accumulo shell -u root -p secret -e "createnamespace geowave"
    accumulo shell -u root -p secret -e "grant NameSpace.CREATE_TABLE -ns geowave -u geowave"
    accumulo shell -u root -p secret -e "config -s general.vfs.context.classpath.geowave=hdfs://localhost:9000/accumulo/lib/[^.].*.jar"
    accumulo shell -u root -p secret -e "config -ns geowave -s table.classpath.context=geowave"
  become_user: hadoop
