
- name: download Spark release 2.1.0
  get_url:
    url: '{{ spark_archive_url }}'
    dest: '/home/vagrant/{{ spark_release }}.tgz'
    checksum: '{{ spark_md5 }}'

- name: Unarchive the Spark tar
  unarchive:
    src: '/home/vagrant/{{ spark_release }}.tgz'
    dest: /srv
    owner: hadoop
    group: hadoop

- name: Create required symbolic link
  file:
    src: /srv/{{ spark_release }}
    dest: /srv/spark
    state: link
    owner: hadoop
    group: hadoop

- name: Recursively chown and chmod
  shell: '{{ item }}'
  with_items:
    - chown -R hadoop:hadoop /srv/{{ spark_release }}
    - chown -R hadoop:hadoop /srv/{{ spark_release }}/*
    - chown -R hadoop:hadoop /srv/spark
    - chmod g+w -R /srv/{{ spark_release }}

- name: write Hive config file
  template:
    src: /home/vagrant/shared/devops/templates/hive-site.xml.j2
    dest: /srv/spark-2.1.0-bin-hadoop2.6/conf/hive-site.xml